// <auto-generated />
using System;
using Clothick.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clothick.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240124150230_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Clothick.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Shirts"
                        },
                        new
                        {
                            Id = 23,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Jackets"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Sweaters"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Dresses"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Skirts"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Shorts"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Socks"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Hats"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Scarves"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Belts"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Gloves"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Sunglasses"
                        });
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 21,
                            Name = "White"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Maroon"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Olive"
                        });
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductRatingId")
                        .HasColumnType("int");

                    b.Property<decimal>("StarRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductRatingId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.ProductRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("StarRating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductRatings");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ColorID")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SizeID");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Name = "XXXL"
                        },
                        new
                        {
                            Id = 21,
                            Name = "XXL"
                        },
                        new
                        {
                            Id = 22,
                            Name = "XL"
                        },
                        new
                        {
                            Id = 23,
                            Name = "L"
                        },
                        new
                        {
                            Id = 24,
                            Name = "M"
                        },
                        new
                        {
                            Id = 25,
                            Name = "S"
                        },
                        new
                        {
                            Id = 26,
                            Name = "XS"
                        },
                        new
                        {
                            Id = 27,
                            Name = "15"
                        },
                        new
                        {
                            Id = 28,
                            Name = "16"
                        },
                        new
                        {
                            Id = 29,
                            Name = "17"
                        },
                        new
                        {
                            Id = 30,
                            Name = "18"
                        },
                        new
                        {
                            Id = 31,
                            Name = "19"
                        },
                        new
                        {
                            Id = 32,
                            Name = "20"
                        },
                        new
                        {
                            Id = 33,
                            Name = "21"
                        },
                        new
                        {
                            Id = 34,
                            Name = "22"
                        },
                        new
                        {
                            Id = 35,
                            Name = "23"
                        },
                        new
                        {
                            Id = 36,
                            Name = "24"
                        },
                        new
                        {
                            Id = 37,
                            Name = "25"
                        },
                        new
                        {
                            Id = 38,
                            Name = "26"
                        },
                        new
                        {
                            Id = 39,
                            Name = "27"
                        },
                        new
                        {
                            Id = 40,
                            Name = "28"
                        },
                        new
                        {
                            Id = 41,
                            Name = "29"
                        },
                        new
                        {
                            Id = 42,
                            Name = "30"
                        },
                        new
                        {
                            Id = 43,
                            Name = "31"
                        },
                        new
                        {
                            Id = 44,
                            Name = "32"
                        },
                        new
                        {
                            Id = 45,
                            Name = "33"
                        },
                        new
                        {
                            Id = 46,
                            Name = "34"
                        },
                        new
                        {
                            Id = 47,
                            Name = "35"
                        },
                        new
                        {
                            Id = 48,
                            Name = "36"
                        },
                        new
                        {
                            Id = 49,
                            Name = "37"
                        },
                        new
                        {
                            Id = 50,
                            Name = "38"
                        },
                        new
                        {
                            Id = 51,
                            Name = "39"
                        },
                        new
                        {
                            Id = 52,
                            Name = "40"
                        },
                        new
                        {
                            Id = 53,
                            Name = "41"
                        },
                        new
                        {
                            Id = 54,
                            Name = "42"
                        },
                        new
                        {
                            Id = 55,
                            Name = "43"
                        },
                        new
                        {
                            Id = 56,
                            Name = "44"
                        },
                        new
                        {
                            Id = 57,
                            Name = "45"
                        },
                        new
                        {
                            Id = 58,
                            Name = "46"
                        },
                        new
                        {
                            Id = 59,
                            Name = "47"
                        },
                        new
                        {
                            Id = 60,
                            Name = "48"
                        },
                        new
                        {
                            Id = 61,
                            Name = "49"
                        },
                        new
                        {
                            Id = 62,
                            Name = "50"
                        },
                        new
                        {
                            Id = 63,
                            Name = "51"
                        },
                        new
                        {
                            Id = 64,
                            Name = "52"
                        },
                        new
                        {
                            Id = 65,
                            Name = "53"
                        },
                        new
                        {
                            Id = 66,
                            Name = "54"
                        },
                        new
                        {
                            Id = 67,
                            Name = "55"
                        },
                        new
                        {
                            Id = 68,
                            Name = "56"
                        },
                        new
                        {
                            Id = 69,
                            Name = "57"
                        },
                        new
                        {
                            Id = 70,
                            Name = "58"
                        },
                        new
                        {
                            Id = 71,
                            Name = "59"
                        },
                        new
                        {
                            Id = 72,
                            Name = "60"
                        });
                });

            modelBuilder.Entity("Clothick.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b14c9eaf-8d20-4042-abf8-ec3a5af8c093"),
                            ConcurrencyStamp = "c250c0db-cc00-4e86-a93c-4dcfefc5ccde",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("20048768-9e40-4cdc-8762-a822f5fe9d3e"),
                            ConcurrencyStamp = "623106b4-1fef-48d9-974a-293cfe3aa05b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("f05a2392-743b-4025-84fe-1dd1822836e5"),
                            ConcurrencyStamp = "85610028-213b-4bac-badd-2784cc93133d",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.ProductRating", "ProductRating")
                        .WithMany("Comments")
                        .HasForeignKey("ProductRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothick.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Image", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("Images")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Product", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.ProductRating", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.Product", "Product")
                        .WithMany("ProductRatings")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothick.Domain.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothick.Domain.Entities.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothick.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Clothick.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Color", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductRatings");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.ProductRating", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Clothick.Domain.Entities.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
